# -*- coding: utf-8 -*-
"""image2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-muSlT3AIFvDm49eQC8NHaekKuYBLPq
"""

import numpy as np
import matplotlib.pyplot as plt

img1 = np.full((640, 640), 140)

plt.imshow(img1, cmap='gray', vmin=0, vmax=255)
plt.title("value = 140")
plt.axis("off")

plt.show()

img1 = np.full((640, 640), 0)
img2 = np.full((640, 640), 200)

vertical = np.vstack((img1, img2))

plt.figure()
plt.imshow(vertical, cmap='gray', vmin=0, vmax=255)
plt.title("Vertical Stack")
plt.axis("off")

plt.show()

import cv2

img= cv2.imread("/images.jpg")

height,width,channels=img.shape

gray=np.zeros((height,width),np.uint8)

for i in range(height):
    for j in range(width):
        gray[i,j]=0.299*img[i,j,0]+0.587*img[i,j,1]+0.114*img[i,j,2]


plt.subplot(1, 2, 1)
plt.imshow(img)
plt.title("RGB Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(gray, cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")

plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread("/images.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

height, width, channels = img.shape

gray = np.zeros((height, width), dtype=np.uint8)

for i in range(height):
    for j in range(width):
        R = img[i, j, 0]
        G = img[i, j, 1]
        B = img[i, j, 2]

        gray[i, j] = (R + G + B) // 3

plt.subplot(1, 2, 1)
plt.imshow(img)
plt.title("RGB Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(gray, cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")

plt.show()

gray_average = np.zeros((height, width), dtype=np.float32)
gray_weighted = np.zeros((height, width), dtype=np.float32)

gray_average[i, j] = (R + G + B) / 3

gray_weighted[i, j] = 0.299*R + 0.587*G + 0.114*B

error= np.abs(gray_weighted[i,j]-gray_average[i,j])

precentage_error = (error/np.maximum(gray_weighted,1)*100)

mean_error=np.mean(precentage_error)

print("Average Percentage error:",mean_error,"%")

