# -*- coding: utf-8 -*-
"""Image3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DRSPKr063p3eB8OUBIh36oTVG2RHoKWx
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread("images.jpg")

# Step 4: Convert to grayscale
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

fig, axes = plt.subplots(1, 2, figsize=(10, 5))
axes[0].imshow(img_rgb)
axes[0].set_title("Original")
axes[0].axis("off")

axes[1].imshow(gray_img, cmap="gray")
axes[1].set_title("Grayscale")
axes[1].axis("off")

plt.show()

cv2.imwrite("grayscale_" + "images.jpg", gray_img)

h,w=gray_img.shaope

for i in range(h):
  for j in range(w):
    #transformation

    gray_image[i,j] = log(1+gray_image[i,j])
    gray_image[i,j]=255-gray_image[i,j]

  plt.imshow(gray_image,cmap='gray')
  plt.show()

  log_image = log(1+gray_image)
  c_image= 255 - gray_image

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Upload image
from google.colab import files
uploaded = files.upload()

# Get filename
filename = list(uploaded.keys())[0]

# Read image
img = cv2.imread(filename)

# Convert to grayscale
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Display original grayscale image
plt.imshow(gray_img, cmap='gray')
plt.title("Original Grayscale Image")
plt.axis("off")
plt.show()

# Input border width and color
width = int(input("Enter border width in pixels: "))
color = int(input("Enter border color (0-255): "))

# Add border
gray_border = cv2.copyMakeBorder(
    gray_img,
    width, width, width, width,
    cv2.BORDER_CONSTANT,
    value=color
)

# Display result
plt.imshow(gray_border, cmap='gray')
plt.title("Grayscale Image with Border")
plt.axis("off")
plt.show()