# -*- coding: utf-8 -*-
"""Image4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ma7ERUZFzaWb4yIborgdabIyXKjTRgJG
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Read image in grayscale
img = cv2.imread(filename, 0)

# Log transformation
c = 1
log_img = c * np.log(1 + img.astype(np.float32))

# Normalize result to 0-255
log_img = cv2.normalize(log_img, None, 0, 255, cv2.NORM_MINMAX)
log_img = log_img.astype(np.uint8)

# Display
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(log_img, cmap='gray')
plt.title("Log Transformed Image")
plt.axis("off")

plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Read image in grayscale
img = cv2.imread(filename, 0)

# Input gamma
gamma = float(input("Enter gamma value: "))

# Normalize image to 0-1
normalized = img / 255.0

# Power law transformation
c = 1
gamma_img = c * (normalized ** gamma)

# Convert back to 0-255
gamma_img = (gamma_img * 255).astype(np.uint8)

# Display
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(gamma_img, cmap='gray')
plt.title("Gamma Transformed Image")
plt.axis("off")

plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Read image in grayscale
img = cv2.imread(filename, 0)

# Input ranges from user
r1 = int(input("Enter input lower intensity: "))
r2 = int(input("Enter input upper intensity: "))

# Output ranges from user
s1 = int(input("Enter output lower intensity: "))
s2 = int(input("Enter output upper intensity: "))

# Contrast stretching
output = np.zeros_like(img, dtype=np.float32)

# Pixels below input range
output[img < r1] = s1

# Pixels above input range
output[img > r2] = s2

# Pixels inside input range
mask = (img >= r1) & (img <= r2)

output[mask] = s1 + ((img[mask] - r1) / (r2 - r1)) * (s2 - s1)

# Convert to uint8
output = np.clip(output, 0, 255).astype(np.uint8)

# Display
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(output, cmap='gray')
plt.title("Contrast Stretched Image")
plt.axis("off")

plt.show()