# -*- coding: utf-8 -*-
"""Image1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HGrU-WMPQe25SxxZckqpPvxZauPemsr7
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Read image as grayscale
gray_img = cv2.imread(filename, 0)

# ---------------- CASE 1 ----------------
# Mean intensity as threshold
mean_threshold = np.mean(gray_img)

binary_mean = np.where(
    gray_img >= mean_threshold, 255, 0
).astype(np.uint8)

print("Case 1")
print("Mean Intensity (Threshold):", mean_threshold)

# ---------------- CASE 2 ----------------
# User input threshold
user_threshold = int(input("Enter threshold value (0-255): "))

binary_user = np.where(
    gray_img >= user_threshold, 255, 0
).astype(np.uint8)

# ---------------- DISPLAY ----------------
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(gray_img, cmap='gray')
plt.title("Original Grayscale")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(binary_mean, cmap='gray')
plt.title("Binary - Mean Threshold")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(binary_user, cmap='gray')
plt.title("Binary - User Threshold")
plt.axis("off")

plt.show()